`[✓] fix(acts/sc/form): broken import in FormLauncher`
**ERROR:**
Compilation error due to an unrecognized  import in SC_FormLauncherActivity.

**CAUSE:**
Got away in the merge conflict; it refers to the now split Utilities class

**FIX:**
Organize imports in SC_FormLauncherActivity